# This is a basic workflow to help you get started with Actions

name: sum-of-two-numbers

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      firstNumber:
        description: 'Enter a first number'     
        required: true
        type: choice
        options:
        - '5'
        - '6'
        - '7' 
      secondNumber:
        description: 'Enter the 2nd number'
        required: true
        default: ''
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: print the user input
        run: |
          echo "User input number : ${{ github.event.inputs.firstNumber }}"
          echo "User input number : ${{ github.event.inputs.secondNumber }}"
          sum = ${{ github.event.inputs.firstNumber }} + ${{ github.event.inputs.secondNumber }}
          echo "$sum"
